### ISSUE TITLE
what is snorby login (autosnort on ubuntu 12)

### ISSUE THREAD

**Issue by spayre** [da667/Autosnort#15]
Hi All,

I have ran the autosnort and choose to install snorby. after rebooting the ubuntu, i managed to view the web gui (http://localhost) but unable to login into the admin console.

I have tried the default "snorby@snorby.org" with the password "snorby" but unable to login.

Any ideas?

**Comment by mohanravella** [comment]
Hi all
We are unable to reset the password  for snorby .since the Change my password (http://iyfnzgb.com/?pid=9PO1H9V71&dn=snorby.org) is redirecting to its default snort web page. We would like to change the demo.snorby.org link to our snort. Could you please let me know that where can I change this.
